#!//bin/bash

## the -B option that supposed to read bed file in tabix doesnt work for me
## we re-create here with a awk-ing the region string out of the bed and using xargs to run tabix
## on each line in the bed file


if [ $# != 2 ]
  then
    echo "tabix-bed file.gz test.bed"
    exit
fi

VCF=$1
BED=$2

if [ ! -f $VCF  ]
then
echo "$VCF doesn't exist!"
exit
fi

if [ ! -f $BED  ]
then
echo "$BED doesn't exist!"
exit
fi

awk '{print $1 ":"$2"-"$3}' $BED| xargs -I  file echo tabix   $VCF file | bash